name: 未知题目的报告（错误码`10001`）
description: 如果遇到“检测到不支持的题目类型”错误，选择此模板。
title: '[Bug]: 未知的问题类型'
labels: ['bug', 'unknown problem type']
assignees:
  - immccn123
body:
  - type: textarea
    attributes:
      label: 请简要描述您在完成什么课程的时候遇到了这个问题
      description: 若您不知道在哪一课，请直接粘贴课程标题，如“数式运算与化简求值”
      placeholder: 在初中人教版九下物理第一颗（走进实验室）的 专题-刻度尺
    validations:
      required: true
  - type: textarea
    attributes:
      label: 出错时的输出
      # description: 
      placeholder: |
        {
          "problemId": "367f2ad1-a8cb-4f63-80d0-ba6576b59aa6",
          "pool": "goal",
          "continuity": false,
          "goalId": "0e0114f9-9a9f-46e3-942e-2442f48e8cf4",
          ...
      render: jsonc
    validations:
      required: true
